### ISSUE TITLE
SSL version error on creation

### ISSUE THREAD

**Issue by vindia** [pepijn/omni_kassa#8]
When I do `omnikassa.perform` I get the following error (both locally as in my production environment)

    SSL_connect returned=1 errno=0 state=unknown state: wrong version number

I think this is due to https://github.com/pepijn/omni_kassa/blob/master/lib/omni_kassa/request.rb#L35 where you specify `ssl_version: :SSLv3` but I don't think the Rabobank server supports this (anymore). 

It does work when I use the direct HTTP request, without specifying the `ssl_version`, like this:

    render text: HTTParty.post(OmniKassa.url, query: omnikassa.query).body

Based on the comment you've only included this for TravisCI, so I'm a bit hesitant to create a pull for this, but if you have an idea how to fix this I'm glad to help.

**Comment by pepijn** [comment]
Please make a pull request with your fix, SSLv3 is very bad!
